name: mkUtilsLegacy
description: mkUtilsLegacy is a lib for plugins development. By Mikael with help of Eduard and Koddy.
version: 3.0.0
softdepend: [ Vault ]
load: POSTWORLD
authors: [ Mikael, Eduard, Koddy ]
main: com.mikael.mkutilslegacy.spigot.UtilsMain

commands:
  mkutils:
    aliases:
      - mkutilslegacy
    description: Shows mkUtilsLegacy version.
    usage: /mkutils
    permission: mkutils.defaultperm