package com.mikael.mkutilslegacy.spigot.enums

/**
 * @author KoddyDev
 */
enum class MinecraftItemName(val translatedName: String) {
    WHITE_STAINED_CLAY("Argila Tingida de Branco"),
    ORANGE_STAINED_CLAY("Argila Tingida de Laranja"),
    MAGENTA_STAINED_CLAY("Argila Tingida de Magenta"),
    LIGHT_BLUE_STAINED_CLAY("Argila Tingida de Azul Claro"),
    YELLOW_STAINED_CLAY("Argila Tingida de Amarelo"),
    LIME_STAINED_CLAY("Argila Tingida de Verde Limão"),
    PINK_STAINED_CLAY("Argila Tingida de Rosa"),
    GRAY_STAINED_CLAY("Argila Tingida de Cinza"),
    LIGHT_GRAY_STAINED_CLAY("Argila Tingida de Cinza Claro"),
    CYAN_STAINED_CLAY("Argila Tingida de Ciano"),
    PURPLE_STAINED_CLAY("Argila Tingida de Lilás"),
    BLUE_STAINED_CLAY("Argila Tingida de Azul"),
    BROWN_STAINED_CLAY("Argila Tingida de Marrom"),
    GREEN_STAINED_CLAY("Argila Tingida de Verde"),
    RED_STAINED_CLAY("Argila Tingida de Vermelho"),
    BLACK_STAINED_CLAY("Argila Tingida de Preto"),

    STAINED_GLASS("Vidro Tingido"),
    WHITE_STAINED_GLASS("Vidro Tingido de Branco"),
    ORANGE_STAINED_GLASS("Vidro Tingido de Laranja"),
    MAGENTA_STAINED_GLASS("Vidro Tingido de Magenta"),
    LIGHT_BLUE_STAINED_GLASS("Vidro Tingido de Azul Claro"),
    YELLOW_STAINED_GLASS("Vidro Tingido de Amarelo"),
    LIME_STAINED_GLASS("Vidro Tingido de Verde Limão"),
    PINK_STAINED_GLASS("Vidro Tingido de Rosa"),
    GRAY_STAINED_GLASS("Vidro Tingido de Cinza"),
    LIGHT_GRAY_STAINED_GLASS("Vidro Tingido de Cinza Claro"),
    CYAN_STAINED_GLASS("Vidro Tingido de Ciano"),
    PURPLE_STAINED_GLASS("Vidro Tingido de Lilás"),
    BLUE_STAINED_GLASS("Vidro Tingido de Azul"),
    BROWN_STAINED_GLASS("Vidro Tingido de Marrom"),
    GREEN_STAINED_GLASS("Vidro Tingido de Verde"),
    RED_STAINED_GLASS("Vidro Tingido de Vermelho"),
    BLACK_STAINED_GLASS("Vidro Tingido de Preto"),

    STAINED_GLASS_PANEL("Painel de Vidro Tingido"),
    WHITE_STAINED_GLASS_PANE("Painel de Vidro Tingido de Branco"),
    ORANGE_STAINED_GLASS_PANE("Painel de Vidro Tingido de Laranja"),
    MAGENTA_STAINED_GLASS_PANE("Painel de Vidro Tingido de Magenta"),
    LIGHT_BLUE_STAINED_GLASS_PANE("Painel de Vidro Tingido de Azul Claro"),
    YELLOW_STAINED_GLASS_PANE("Painel de Vidro Tingido de Amarelo"),
    LIME_STAINED_GLASS_PANE("Painel de Vidro Tingido de Verde Limão"),
    PINK_STAINED_GLASS_PANE("Painel de Vidro Tingido de Rosa"),
    GRAY_STAINED_GLASS_PANE("Painel de Vidro Tingido de Cinza"),
    LIGHT_GRAY_STAINED_GLASS_PANE("Painel de Vidro Tingido de Cinza Claro"),
    CYAN_STAINED_GLASS_PANE("Painel de Vidro Tingido de Ciano"),
    PURPLE_STAINED_GLASS_PANE("Painel de Vidro Tingido de Lilás"),
    BLUE_STAINED_GLASS_PANE("Painel de Vidro Tingido de Azul"),
    BROWN_STAINED_GLASS_PANE("Painel de Vidro Tingido de Marrom"),
    GREEN_STAINED_GLASS_PANE("Painel de Vidro Tingido de Verde"),
    RED_STAINED_GLASS_PANE("Painel de Vidro Tingido de Vermelho"),
    BLACK_STAINED_GLASS_PANE("Painel de Vidro Tingido de Preto"),

    WHITE_CARPET("Carpete Branco"),
    ORANGE_CARPET("Carpete Laranja"),
    MAGENTA_CARPET("Carpete Magenta"),
    LIGHT_BLUE_CARPET("Carpete Azul Claro"),
    YELLOW_CARPET("Carpete Amarelo"),
    LIME_CARPET("Carpete Verde Limão"),
    PINK_CARPET("Carpete Rosa"),
    GRAY_CARPET("Carpete Cinza"),
    LIGHT_GRAY_CARPET("Carpete Cinza Claro"),
    CYAN_CARPET("Carpete Ciano"),
    PURPLE_CARPET("Carpete Lilás"),
    BLUE_CARPET("Carpete Azul"),
    BROWN_CARPET("Carpete Marrom"),
    GREEN_CARPET("Carpete Verde"),
    RED_CARPET("Carpete Vermelho"),
    BLACK_CARPET("Carpete Preto"),

    WHITE_WOOL("Lã Branca"),
    ORANGE_WOOL("Lã Laranja"),
    MAGENTA_WOOL("Lã Magenta"),
    LIGHT_BLUE_WOOL("Lã Azul Claro"),
    YELLOW_WOOL("Lã Amarela"),
    LIME_WOOL("Lã Verde Limão"),
    PINK_WOOL("Lã Rosa"),
    GRAY_WOOL("Lã Cinza"),
    LIGHT_GRAY_WOOL("Lã Cinza Claro"),
    CYAN_WOOL("Lã Ciano"),
    PURPLE_WOOL("Lã Lilás"),
    BLUE_WOOL("Lã Azul"),
    BROWN_WOOL("Lã Marrom"),
    GREEN_WOOL("Lã Verde"),
    RED_WOOL("Lã Vermelha"),
    BLACK_WOOL("Lã Preta"),

    INK_SACK("Bolsa de Tinta"),
    WHITE_DYE("Farinha de Osso"),
    ORANGE_DYE("Corante Laranja"),
    MAGENTA_DYE("Corante Magenta"),
    LIGHT_BLUE_DYE("Corante Azul Claro"),
    YELLOW_DYE("Corante Amarelo"),
    LIME_DYE("Corante Verde Limão"),
    PINK_DYE("Corante Rosa"),
    GRAY_DYE("Corante Cinza"),
    LIGHT_GRAY_DYE("Corante Cinza Claro"),
    CYAN_DYE("Corante Ciano"),
    PURPLE_DYE("Corante Lilás"),
    BLUE_DYE("Lápis-Lazúli"),
    BROWN_DYE("Sementes de Cacau"),
    GREEN_DYE("Corante Verde"),
    RED_DYE("Corante Vermelho"),
    BLACK_DYE("Corante Preto"),

    AIR("Ar"),
    APPLE("Maçã"),
    ARMOR_STAND("Suporte de Armaduras"),
    ARROW("Flecha"),
    BAKED_POTATO("Batata Assada"),
    BEEF("Bife Assado"),
    BLAZE_POWDER("Pó de Blaze"),
    BLAZE_ROD("Vara Incandescente"),
    BOAT("Bote"),
    BONE("Osso"),
    BOOK("Livro"),
    BOOKSHELF("Estante de Livros"),
    BOW("Arco"),
    BOWL("Tigela"),
    BREAD("Pão"),
    BREWING_STAND("Suporte de Poções"),
    BREWING_STAND_ITEM("Suporte de Poções"),
    BRICK("Tijolo"),
    BUCKET("Balde"),
    CACTUS("Cacto"),
    CAKE("Bolo"),
    CARROT("Cenoura"),
    CARROT_ON_A_STICK("Cenoura no Palito"),
    CAULDRON("Caldeirão"),
    CHAINMAIL_BOOTS("Botas de Malha"),
    CHAINMAIL_CHESTPLATE("Peitoral de Malha"),
    CHAINMAIL_HELMET("Capacete de Malha"),
    CHAINMAIL_LEGGINGS("Calças de Malha"),
    CHARCOAL("Carvão Vegetal"),
    CHEST("Baú"),
    CHICKEN("Carne de Frango Crua"),
    CLAY("Argila"),
    CLAY_BALL("Bola de Argila"),
    CLOCK("Relógio"),
    COAL("Carvão"),
    COAL_BLOCK("Bloco de Carvão"),
    COAL_ORE("Minério de Carvão"),
    COBBLESTONE("Pedregulho"),
    COBBLESTONE_WALL("Muro de Pedregulho"),
    COCOA_BEANS("Sementes de Cacau"),
    COMMAND_BLOCK("Bloco de Comando"),
    COMPASS("Bússola"),
    COOKED_BEEF("Carne Assada"),
    COOKED_CHICKEN("Frango Assado"),
    COOKED_FISH("Peixe Assado"),
    COOKED_MUTTON("Carne de Carneiro Assada"),
    COOKED_PORKCHOP("Costela de Porco Assada"),
    CROPS("Semente"),
    DARK_OAK_DOOR("Porta de Carvalho Escuro"),
    DARK_OAK_DOOR_ITEM("Porta de Carvalho Escuro"),
    DARK_OAK_FENCE("Cerca de Carvalho Escuro"),
    DARK_OAK_FENCE_GATE("Portão de Carvalho Escuro"),
    DARK_OAK_STAIRS("Escada de Carvalho Escuro"),
    DAYLIGHT_DETECTOR("Sensor de Luz Solar"),
    DEAD_BUSH("Arbusto Morto"),
    DETECTOR_RAIL("Trilho Detector"),
    DIAMOND("Diamante"),
    DIAMOND_AXE("Machado de Diamante"),
    DIAMOND_BARDING("Armadura de Cavalo de Diamante"),
    DIAMOND_BLOCK("Bloco de Diamante"),
    DIAMOND_BOOTS("Botas de Diamante"),
    DIAMOND_CHESTPLATE("Peitoral de Diamante"),
    DIAMOND_HELMET("Capacete de Diamante"),
    DIAMOND_HOE("Enxada de Diamante"),
    DIAMOND_LEGGINGS("Calças de Diamante"),
    DIAMOND_ORE("Minério de Diamante"),
    DIAMOND_PICKAXE("Picareta de Diamante"),
    DIAMOND_SPADE("Pá de Diamante"),
    DIAMOND_SWORD("Espada de Diamante"),
    DIODE("Repetidor de Redstone"),
    DIODE_BLOCK_OFF("Repetidor de Redstone"),
    DIODE_BLOCK_ON("Repetidor de Redstone"),
    DIRT("Terra"),
    DISPENSER("Distribuidor"),
    DOUBLE_PLANT("Planta Dupla"),
    DOUBLE_STEP("Degrau Duplo"),
    DOUBLE_STONE_SLAB2("Degrau Duplo"),
    DRAGON_EGG("Ovo do Dragão"),
    DROPPER("Liberador"),
    EGG("Ovo"),
    EMERALD("Esmeralda"),
    EMERALD_BLOCK("Bloco de Esmeralda"),
    EMERALD_ORE("Minério de Esmeralda"),
    EMPTY_MAP("Mapa Vazio"),
    ENCHANTED_BOOK("Livro Encantado"),
    ENCHANTMENT_TABLE("Mesa de Encantamentos"),
    ENDER_CHEST("Baú do Fim"),
    ENDER_PEARL("Pérola do Fim"),
    ENDER_PORTAL_FRAME("Portal do Fim"),
    ENDER_STONE("Pedra do Fim"),
    EXP_BOTTLE("Frasco de Experiência"),
    EXPLOSIVE_MINECART("Carrinho de Minas Explosivo"),
    EYE_OF_ENDER("Olho do Fim"),
    FEATHER("Pena"),
    FENCE("Cerca"),
    FENCE_GATE("Portão"),
    FERMENTED_SPIDER_EYE("Olho de Aranha Fermentado"),
    FIRE("Fogo"),
    FIREBALL("Bola de Fogo"),
    FIREWORK("Fogos de Artifício"),
    FIREWORK_CHARGE("Estrela de Fogos de Artifício"),
    FISHING_ROD("Vara de Pescar"),
    ANVIL("Bigorna"),
    SLIGHTLY_DAMAGED_ANVIL("Bigorna Danificada"),
    VERY_DAMAGED_ANVIL("Bigorna Muito Danificada"),
    FLINT("Pederneira"),
    FLINT_AND_STEEL("Isqueiro"),
    FLOWER_POT("Vaso de Flores"),
    FURNACE("Fornalha"),
    GHAST_TEAR("Lágrima de Ghast"),
    GLASS("Vidro"),
    GLASS_BOTTLE("Frasco de Vidro"),
    GLOWING_REDSTONE_ORE("Minério de Redstone Brilhante"),
    GLOWSTONE("Pedra Luminosa"),
    GLOWSTONE_DUST("Pó de Pedra Luminosa"),
    GOLD_AXE("Machado de Ouro"),
    GOLD_BARDING("Armadura de Cavalo de Ouro"),
    GOLD_BLOCK("Bloco de Ouro"),
    GOLD_BOOTS("Botas de Ouro"),
    GOLD_CHESTPLATE("Peitoral de Ouro"),
    GOLD_HELMET("Capacete de Ouro"),
    GOLD_HOE("Enxada de Ouro"),
    GOLD_INGOT("Lingote de Ouro"),
    GOLD_LEGGINGS("Calças de Ouro"),
    GOLD_NUGGET("Pepita de Ouro"),
    GOLD_ORE("Minério de Ouro"),
    GOLD_PICKAXE("Picareta de Ouro"),
    GOLD_PLATE("Placa de Pressão de Ouro"),
    GOLD_RECORD("Disco de Música"),
    GOLD_SPADE("Pá de Ouro"),
    GOLD_SWORD("Espada de Ouro"),
    GOLDEN_APPLE("Maçã Dourada"),
    CAP_APPLE("Maçã Dourada Encantada"),
    GOLDEN_CARROT("Cenoura Dourada"),
    GRASS("Grama"),
    GRAVEL("Cascalho"),
    GREEN_RECORD("Disco de Música"),
    GRILLED_PORK("Costela de Porco Assada"),
    HARD_CLAY("Argila Endurecida"),
    HAY_BLOCK("Fardo de Feno"),
    HOPPER("Funil"),
    HOPPER_MINECART("Carrinho de Minas com Funil"),
    HUGE_MUSHROOM_1("Cogumelo"),
    HUGE_MUSHROOM_2("Cogumelo"),
    ICE("Gelo"),
    IRON_AXE("Machado de Ferro"),
    IRON_BARDING("Armadura de Cavalo de Ferro"),
    IRON_BLOCK("Bloco de Ferro"),
    IRON_BOOTS("Botas de Ferro"),
    IRON_CHESTPLATE("Peitoral de Ferro"),
    IRON_DOOR("Porta de Ferro"),
    IRON_DOOR_BLOCK("Porta de Ferro"),
    IRON_FENCE("Cerca de Ferro"),
    IRON_HELMET("Capacete de Ferro"),
    IRON_HOE("Enxada de Ferro"),
    IRON_INGOT("Lingote de Ferro"),
    IRON_LEGGINGS("Calças de Ferro"),
    IRON_ORE("Minério de Ferro"),
    IRON_PICKAXE("Picareta de Ferro"),
    IRON_PLATE("Placa de Pressão de Ferro"),
    IRON_SPADE("Pá de Ferro"),
    IRON_SWORD("Espada de Ferro"),
    ITEM_FRAME("Moldura"),
    JACK_O_LANTERN("Abóbora Lanterna"),
    JUKEBOX("Toca-Discos"),
    JUNGLE_DOOR("Porta de Madeira da Selva"),
    JUNGLE_DOOR_ITEM("Porta de Madeira da Selva"),
    JUNGLE_FENCE("Cerca de Madeira da Selva"),
    JUNGLE_FENCE_GATE("Portão de Madeira da Selva"),
    JUNGLE_WOOD_STAIRS("Escada de Madeira da Selva"),
    LADDER("Escada"),
    LAPIS_BLOCK("Bloco de Lápis-Lazúli"),
    LAPIS_ORE("Minério de Lápis-Lazúli"),
    LAVA("Lava"),
    LAVA_BUCKET("Balde de Lava"),
    LEASH("Laço"),
    LEATHER("Couro"),
    LEATHER_BOOTS("Botas de Couro"),
    LEATHER_CHESTPLATE("Túnica de Couro"),
    LEATHER_HELMET("Capacete de Couro"),
    LEATHER_LEGGINGS("Calças de Couro"),
    LEAVES("Folhas"),
    LEAVES_2("Folhas"),
    LEVER("Alavanca"),
    LOG("Madeira"),
    LOG_2("Madeira"),
    LONG_GRASS("Grama Alta"),
    MAGMA_CREAM("Creme de Magma"),
    MAP("Mapa"),
    MELON("Melancia"),
    MELON_BLOCK("Bloco de Melancia"),
    MELON_SEEDS("Sementes de Melancia"),
    MELON_STEM("Caule de Melancia"),
    MILK_BUCKET("Balde de Leite"),
    MINECART("Carrinho de Minas"),
    MOB_SPAWNER("Gerador de Monstros"),
    MONSTER_EGG("Bloco de Pedra Infestado"),
    MONSTER_EGGS("Ovo de Monstro"),
    MOSSY_COBBLESTONE("Pedregulho com Musgo"),
    MUSHROOM_SOUP("Sopa de Cogumelo"),
    MUTTON("Carne de Carneiro Cru"),
    MYCEL("Micélio"),
    NAME_TAG("Etiqueta"),
    NETHER_BRICK("Tijolo do Nether"),
    NETHER_BRICK_ITEM("Tijolo do Nether"),
    NETHER_BRICK_STAIRS("Escada de Tijolo do Nether"),
    NETHER_FENCE("Cerca do Nether"),
    NETHER_STALK("Fungo do Nether"),
    NETHER_STAR("Estrela do Nether"),
    NETHER_WARTS("Fungo do Nether"),
    NETHERRACK("Rocha do Nether"),
    NOTE_BLOCK("Bloco Musical"),
    OBSIDIAN("Obsidiana"),
    PACKED_ICE("Gelo Compactado"),
    PAINTING("Pintura"),
    PAPER("Papel"),
    PISTON_BASE("Pistão"),
    PISTON_EXTENSION("Pistão"),
    PISTON_MOVING_PIECE("Pistão"),
    PISTON_STICKY_BASE("Pistão"),
    POISONOUS_POTATO("Batata Venenosa"),
    PORK("Costela de Porco"),
    PORTAL("Portal"),
    POTATO("Batata"),
    POTATO_ITEM("Batata"),
    POTION("Poção"),
    POWERED_MINECART("Carrinho de Minas com Motor"),
    POWERED_RAIL("Trilho Energizado"),
    PRISMARINE("Prismarinho"),
    PRISMARINE_BRICKS("Tijolos de Prismarinho"),
    DARK_PRISMARINE("Prismarinho Escuro"),
    PRISMARINE_CRYSTALS("Cristais de Prismarinho"),
    PRISMARINE_SHARD("Fragmento de Prismarinho"),
    PUMPKIN("Abóbora"),
    PUMPKIN_PIE("Torta de Abóbora"),
    PUMPKIN_SEEDS("Sementes de Abóbora"),
    PUMPKIN_STEM("Caule de Abóbora"),
    QUARTZ("Quartzo"),
    QUARTZ_BLOCK("Bloco de Quartzo"),
    QUARTZ_ORE("Minério de Quartzo"),
    QUARTZ_STAIRS("Escada de Quartzo"),
    RABBIT("Carne de Coelho Cru"),
    COOKED_RABBIT("Carne de Coelho Assado"),
    RABBIT_FOOT("Pé de Coelho"),
    RABBIT_HIDE("Pele de Coelho"),
    RABBIT_STEW("Ensopado de Coelho"),

    RAILS("Trilho"),
    RAW_BEEF("Bife Cru"),
    RAW_CHICKEN("Frango Cru"),
    RAW_FISH("Peixe Cru"),
    RECORD_10("Disco de Música"),
    RECORD_11("Disco de Música"),
    RECORD_12("Disco de Música"),
    RECORD_3("Disco de Música"),
    RECORD_4("Disco de Música"),
    RECORD_5("Disco de Música"),
    RECORD_6("Disco de Música"),
    RECORD_7("Disco de Música"),
    RECORD_8("Disco de Música"),
    RECORD_9("Disco de Música"),
    RED_MUSHROOM("Cogumelo"),
    RED_ROSE("Papoula"),
    RED_SANDSTONE("Arenito Vermelho"),
    RED_SANDSTONE_STAIRS("Escada de Arenito Vermelho"),
    REDSTONE("Redstone"),
    REDSTONE_BLOCK("Bloco de Redstone"),
    REDSTONE_COMPARATOR("Comparador de Redstone"),
    REDSTONE_COMPARATOR_OFF("Comparador de Redstone"),
    REDSTONE_COMPARATOR_ON("Comparador de Redstone"),
    REDSTONE_LAMP_OFF("Lâmpada de Redstone"),
    REDSTONE_LAMP_ON("Lâmpada de Redstone"),
    REDSTONE_ORE("Minério de Redstone"),
    REDSTONE_TORCH_OFF("Tocha de Redstone"),
    REDSTONE_TORCH_ON("Tocha de Redstone"),
    REDSTONE_WIRE("Redstone"),
    ROTTEN_FLESH("Carne Podre"),
    SADDLE("Sela"),
    SAND("Areia"),
    SANDSTONE("Arenito"),
    SANDSTONE_STAIRS("Escada de Arenito"),
    SAPLING("Muda"),
    SEA_LANTERN("Lanterna do Mar"),
    SEEDS("Sementes"),
    SHEARS("Tesoura"),
    SIGN("Placa"),
    SIGN_POST("Placa"),
    SKULL("Cabeça"),
    SKULL_ITEM("Cabeça"),
    SLIME_BALL("Gosma de Slime"),
    SMOOTH_BRICK("Tijolo"),
    SMOOTH_STAIRS("Escada de Tijolo"),
    SNOW("Neve"),
    SNOW_BALL("Bola de Neve"),
    SNOW_BLOCK("Bloco de Neve"),
    SOIL("Terra Arada"),
    SOUL_SAND("Areia de Almas"),
    SPECKLED_MELON("Melancia Encantada"),
    SPECTRAL_ARROW("Flecha Espectral"),
    SPIDER_EYE("Olho de Aranha"),
    SPLASH_POTION("Poção Arremessável"),
    SPONGE("Esponja"),
    SPRUCE_DOOR("Porta de Madeira de Pinheiro"),
    SPRUCE_DOOR_ITEM("Porta de Madeira de Pinheiro"),
    SPRUCE_FENCE("Cerca de Madeira de Pinheiro"),
    SPRUCE_FENCE_GATE("Portão de Madeira de Pinheiro"),
    SPRUCE_WOOD_STAIRS("Escada de Madeira de Pinheiro"),
    STANDING_BANNER("Estandarte"),
    STATIONARY_LAVA("Lava"),
    STATIONARY_WATER("Água"),
    STEP("Laje"),
    STICK("Graveto"),
    STONE("Pedra"),
    GRANITE("Granito"),
    POLISHED_GRANITE("Granito Polido"),
    DIORITE("Diorito"),
    POLISHED_DIORITE("Diorito Polido"),
    ANDESITE("Andesito"),
    POLISHED_ANDESITE("Andesito Polido"),
    STONE_AXE("Machado de Pedra"),
    STONE_BUTTON("Botão de Pedra"),
    STONE_HOE("Enxada de Pedra"),
    STONE_PICKAXE("Picareta de Pedra"),
    STONE_PLATE("Placa de Pressão de Pedra"),
    STONE_SLAB2("Degrau de Pedra"),
    STONE_SPADE("Pá de Pedra"),
    STONE_SWORD("Espada de Pedra"),
    STORAGE_MINECART("Carrinho com Baú"),
    STRING("Linha"),
    STRUCTURE_BLOCK("Bloco de Estrutura"),
    SUGAR("Açúcar"),
    SUGAR_CANE("Cana-de-Açúcar"),
    SUGAR_CANE_BLOCK("Cana-de-Açúcar"),
    SULPHUR("Pólvora"),
    THIN_GLASS("Painel de Vidro"),
    TNT("Dinamite"),
    TORCH("Tocha"),
    TRAP_DOOR("Alçapão"),
    TRAPPED_CHEST("Baú com Armadilha"),
    TRIPWIRE("Linha de Armadilha"),
    TRIPWIRE_HOOK("Gancho de Armadilha"),
    VINE("Vinhas"),
    WALL_BANNER("Estandarte"),
    WALL_SIGN("Placa"),
    WATCH("Relógio"),
    WATER("Água"),
    WATER_BUCKET("Balde de Água"),
    WATER_LILY("Vitória-Régia"),
    WEB("Teia de Aranha"),
    WHEAT("Trigo"),
    WOOD("Tábuas de Madeira"),
    WOOD_AXE("Machado de Madeira"),
    WOOD_BUTTON("Botão de Madeira"),
    WOOD_DOOR("Porta de Madeira"),
    WOOD_DOUBLE_STEP("Degrau Duplo de Madeira"),
    WOOD_HOE("Enxada de Madeira"),
    WOOD_PICKAXE("Picareta de Madeira"),
    WOOD_PLATE("Placa de Pressão de Madeira"),
    WOOD_SPADE("Pá de Madeira"),
    WOOD_STAIRS("Escada de Madeira"),
    WOOD_STEP("Degrau de Madeira"),
    WOOD_SWORD("Espada de Madeira"),
    WOODEN_DOOR("Porta de Madeira"),
    WORKBENCH("Bancada de Trabalho"),
    WRITTEN_BOOK("Livro Escrito"),
    YELLOW_FLOWER("Flor Amarela");

    companion object {
        // 0 -> WHITE
        val mapColorsData = mapOf(
            0 to "WHITE",
            1 to "ORANGE",
            2 to "MAGENTA",
            3 to "LIGHT_BLUE",
            4 to "YELLOW",
            5 to "LIME",
            6 to "PINK",
            7 to "GRAY",
            8 to "LIGHT_GRAY",
            9 to "CYAN",
            10 to "PURPLE",
            11 to "BLUE",
            12 to "BROWN",
            13 to "GREEN",
            14 to "RED",
            15 to "BLACK"
        )

        val mapStonesData = mapOf(
            0 to "STONE",
            1 to "GRANITE",
            2 to "POLISHED_GRANITE",
            3 to "DIORITE",
            4 to "POLISHED_DIORITE",
            5 to "ANDESITE",
            6 to "POLISHED_ANDESITE"
        )

        val mapDirtsData = mapOf(
            0 to "DIRT",
            1 to "COARSE_DIRT",
            2 to "PODZOL"
        )

        val mapSandstonesData = mapOf(
            0 to "SANDSTONE",
            1 to "CHISELED_SANDSTONE",
            2 to "SMOOTH_SANDSTONE"
        )

        val mapQuartzData = mapOf(
            0 to "QUARTZ_BLOCK",
            1 to "CHISELED_QUARTZ_BLOCK",
            2 to "QUARTZ_PILLAR"
        )

        val mapWoodsData = mapOf(
            0 to "OAK_WOOD",
            1 to "SPRUCE_WOOD",
            2 to "BIRCH_WOOD",
            3 to "JUNGLE_WOOD",
            4 to "ACACIA_WOOD",
            5 to "DARK_OAK_WOOD"
        )

        val mapWoodsLeavesData = mapOf(
            0 to "OAK_LEAVES",
            1 to "SPRUCE_LEAVES",
            2 to "BIRCH_LEAVES",
            3 to "JUNGLE_LEAVES"
        )

        val mapWoodsLeavesData2 = mapOf(
            0 to "ACACIA_LEAVES",
            1 to "DARK_OAK_LEAVES"
        )

        val mapWoodsSaplingsData = mapOf(
            0 to "OAK_SAPLING",
            1 to "SPRUCE_SAPLING",
            2 to "BIRCH_SAPLING",
            3 to "JUNGLE_SAPLING",
            4 to "ACACIA_SAPLING",
            5 to "DARK_OAK_SAPLING"
        )

        val mapWoodsLogsData = mapOf(
            0 to "OAK_LOG",
            1 to "SPRUCE_LOG",
            2 to "BIRCH_LOG",
            3 to "JUNGLE_LOG"
        )

        val mapWoodsLogsData2 = mapOf(
            0 to "ACACIA_LOG",
            1 to "DARK_OAK_LOG"
        )

        val mapWoodsPlanksSlabsData = mapOf(
            0 to "OAK_SLAB",
            1 to "SPRUCE_SLAB",
            2 to "BIRCH_SLAB",
            3 to "JUNGLE_SLAB",
            4 to "ACACIA_SLAB",
            5 to "DARK_OAK_SLAB"
        )

        val mapPrismarinesData = mapOf(
            0 to "PRISMARINE",
            1 to "PRISMARINE_BRICKS",
            2 to "DARK_PRISMARINE"
        )

        val mapStoneBrinksData = mapOf(
            0 to "STONE_BRICKS",
            1 to "MOSSY_STONE_BRICKS",
            2 to "CRACKED_STONE_BRICKS",
            3 to "CHISELED_STONE_BRICKS"
        )

        val mapRedSandstonesData = mapOf(
            0 to "RED_SANDSTONE",
            1 to "CHISELED_RED_SANDSTONE",
            2 to "SMOOTH_RED_SANDSTONE"
        )

        val mapSpongesData = mapOf(
            0 to "SPONGE",
            1 to "WET_SPONGE"
        )

        val mapGrassData = mapOf(
            1 to "GRASS",
            2 to "FERN"
        )

        val mapFlowersData = mapOf(
            0 to "POPPY",
            1 to "BLUE_ORICHID",
            2 to "ALLIUM",
            3 to "AZURE_BLUET",
            4 to "RED_TULIP",
            5 to "ORANGE_TULIP",
            6 to "WHITE_TULIP",
            7 to "PINK_TULIP",
            8 to "OXEYE_DAISY"
        )

        val mapMonsterEggsData = mapOf(
            0 to "STONE_MONSTER_EGG",
            1 to "COBBLESTONE_MONSTER_EGG",
            2 to "STONE_BRICK_MONSTER_EGG",
            3 to "MOSSY_STONE_BRICK_MONSTER_EGG",
            4 to "CRACKED_STONE_BRICK_MONSTER_EGG",
            5 to "CHISELED_STONE_BRICK_MONSTER_EGG"
        )

        val mapAnvilData = mapOf(
            0 to "ANVIL",
            1 to "SLIGHTLY_DAMAGED_ANVIL",
            2 to "VERY_DAMAGED_ANVIL"
        )

        val mapDoublePlantData = mapOf(
            0 to "SUNFLOWER",
            1 to "LILAC",
            2 to "DOUBLE_TALLGRASS",
            3 to "LARGE_FERN",
            4 to "ROSE_BUSH",
            5 to "PEONY"
        )

        val mapSkullData = mapOf(
            0 to "SKELETON_SKULL",
            1 to "WITHER_SKELETON_SKULL",
            2 to "ZOMBIE_HEAD",
            3 to "HEAD"
        )

        val mapBannerData = mapOf(
            0 to "WHITE_BANNER",
            1 to "ORANGE_BANNER",
            2 to "MAGENTA_BANNER",
            3 to "LIGHT_BLUE_BANNER",
            4 to "YELLOW_BANNER",
            5 to "LIME_BANNER",
            6 to "PINK_BANNER",
            7 to "GRAY_BANNER",
            8 to "LIGHT_GRAY_BANNER",
            9 to "CYAN_BANNER",
            10 to "PURPLE_BANNER",
            11 to "BLUE_BANNER",
            12 to "BROWN_BANNER",
            13 to "GREEN_BANNER",
            14 to "RED_BANNER",
            15 to "BLACK_BANNER"
        )

        /*
        val mapSpawnEggData = mapOf(
            50 to "SPAWN_CREEPER",
            51 to "SPAWN_SKELETON",
            52 to "SPAWN_SPIDER",
            54 to "SPAWN_ZOMBIE",
            55 to "SPAWN_SLIME",
            56 to "SPAWN_GHAST",
            57 to "SPAWN_ZOMBIE_PIGMAN",
            58 to "SPAWN_ENDERMAN",
            59 to "SPAWN_CAVE_SPIDER",
            60 to "SPAWN_SILVERFISH",
            61 to "SPAWN_BLAZE",
            62 to "SPAWN_MAGMA_CUBE",
            65 to "SPAWN_BAT",
            66 to "SPAWN_WITCH",
            67 to "SPAWN_ENDERMITE",
            68 to "SPAWN_GUARDIAN",
            90 to "SPAWN_PIG",
            91 to "SPAWN_SHEEP",
            92 to "SPAWN_COW",
            93 to "SPAWN_CHICKEN",
            94 to "SPAWN_SQUID",
            95 to "SPAWN_WOLF",
            96 to "SPAWN_MOOSHROON",
            98 to "SPAWN_OCELOT",
            100 to "SPAWN_HORSE",
            101 to "SPAWN_RABBIT",
            120 to "SPAWN_VILLAGER"
        )

         */

        val mapFishData = mapOf(
            0 to "RAW_FISH",
            1 to "RAW_SALMON",
            2 to "CLOWNFISH",
            3 to "PUFFERFISH"
        )

        val mapCookedFishData = mapOf(
            0 to "COOKED_FISH",
            1 to "COOKED_SALMON"
        )

        /**
         * [RankupItem.GOLDEN_APPLE], [RankupItem.CAP_APPLE].
         */
        val mapGoldenAppleData = mapOf(
            0 to "GOLDEN_APPLE",
            1 to "CAP_APPLE"
        )
    }

}